=begin
#Oscar Taracena
#BEWD Homework #3 - Grandma. Program was to use rand number generator, looping and conditional logic to have grandma respond either by:
saying can't hear you, not since <year, generated by random number generator> or good bye from the program. Note since I was repeating
output over and over, i deceided to create a method grandma with no return value at all, just with output text to keep repetion down and
for refaction purposes. I used 1 to equal true, and then to equal false - took the value of ask_again and subtracted 1 against it to get
 value of 0. 
=end

def grandma()# method - done for brevity/refactoring purposes
    puts "<Grandma's silence> - need to say BYE  or her dementia kicks in and loops"
    puts "the conversation!!" 
end


ask_again = 1 #replaces and becomes true/false in the code
puts "Grandma says: Hello sonny how are you? "
input1 = gets.chomp

while ask_again 
    
        year = rand(1930..1950)#random number generator from 1930 to 1950
        	#1st cond. handles lowercase input
            if input1 != input1.upcase   
                puts "Huh I cannot hear you!!"
            grandma #method call

            #end
              #2nd cond. handles upcase and not BYE   
             elsif input1 == input1.upcase && input1 != 'BYE'
                puts "NO, NOT SINCE #{year}!!!"
                grandma #method call
            #end
			#final condition to test for
            else input1 == 'BYE'
                puts "BYE!!!"
                ask_again = ask_again - 1
                break
            end
    input1 = gets.chomp
end


